"""create avaliations table

Revision ID: 8b13948e018a
Revises: 9b416e697139
Create Date: 2024-10-09 15:46:09.137008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b13948e018a'
down_revision: Union[str, None] = '9b416e697139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliations',
    sa.Column('avaliation_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinical_history_id', sa.Integer(), nullable=False),
    sa.Column('clinical_examination_id', sa.Integer(), nullable=False),
    sa.Column('physiotherapy_diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('prognosis_id', sa.Integer(), nullable=False),
    sa.Column('treatment_plan_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinical_examination_id'], ['clinical_examinations.exam_id'], ),
    sa.ForeignKeyConstraint(['clinical_history_id'], ['clinical_histories.history_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['physiotherapy_diagnosis_id'], ['physiotherapy_diagnosis.diagnosis_id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.professional_id'], ),
    sa.ForeignKeyConstraint(['prognosis_id'], ['prognosis.prognosis_id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatments_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('avaliation_id')
    )
    op.add_column('evolution_records', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evolution_records', 'date')
    op.drop_table('avaliations')
    # ### end Alembic commands ###
