"""right class Evolution Records

Revision ID: 9b416e697139
Revises: c88cf09971b2
Create Date: 2024-09-06 15:07:37.795766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b416e697139'
down_revision: Union[str, None] = 'c88cf09971b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evolution_records', sa.Column('health_status_evolution', sa.String(), nullable=False))
    op.drop_column('evolution_records', 'heath_status_evolution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evolution_records', sa.Column('heath_status_evolution', sa.VARCHAR(), nullable=False))
    op.drop_column('evolution_records', 'health_status_evolution')
    # ### end Alembic commands ###
